services:
  db:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kaiketsu
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # データ永続化
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro # 初期化スクリプト

volumes:
  db-data:
